# -*- coding: utf-8 -*-
#
# ansible-flow documentation build configuration file, created by
# sphinx-quickstart on Wed Dec  2 10:24:47 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import sphinx_rtd_theme

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../'))

# -- General configuration ------------------------------------------------

extensions = ['sphinxcontrib.spelling']
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'

# General information about the project.
project = u'ansible-flow'
copyright = u'2015, John Vrbanac'
author = u'John Vrbanac'

version = u'0.1.0'
release = u'0.1.0'

language = None

exclude_patterns = ['_build']

pygments_style = 'sphinx'

todo_include_todos = False
spelling_word_list_filename = 'spellcheck_words.txt'

# -- Options for HTML output ----------------------------------------------
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
htmlhelp_basename = 'ansible-flowdoc'

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {
}

latex_documents = [
    (master_doc, 'ansible-flow.tex', u'ansible-flow Documentation',
     u'John Vrbanac', 'manual'),
]

# -- Options for manual page output ---------------------------------------
man_pages = [
    (master_doc, 'ansible-flow', u'ansible-flow Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------
texinfo_documents = [
    (master_doc, 'ansible-flow', u'ansible-flow Documentation',
     author, 'ansible-flow', 'One line description of project.',
     'Miscellaneous'),
]
